import type { FolderRule } from '../database/schema';

export interface SieveOptions {
  readonly notifyScript: string;
  readonly junkFolder: string;
}

function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function quoteMatch(value: string, { prefix = '', suffix = '' } = {}): string {
  return `"${prefix}${value.replace(/([\\"*?])/g, '\\$1')}${suffix}"`;
}

function headerFor(field: string): string | null {
  switch (field) {
    case 'sender':
      return 'from';
    case 'subject':
      return 'subject';
    case 'recipient':
      return 'to';
    default:
      return null;
  }
}

function condition(rule: FolderRule): string | null {
  const header = headerFor(rule.conditionField);

  if (header === null) {
    return null;
  }

  const name = quote(header);

  switch (rule.conditionOperator) {
    case 'contains':
      return `header :contains ${name} ${quote(rule.conditionValue)}`;
    case 'equals':
      return `header :is ${name} ${quote(rule.conditionValue)}`;
    case 'starts_with':
      return `header :matches ${name} ${quoteMatch(rule.conditionValue, { suffix: '*' })}`;
    case 'ends_with':
      return `header :matches ${name} ${quoteMatch(rule.conditionValue, { prefix: '*' })}`;
    default:
      return null;
  }
}

function body(rule: FolderRule, notify: string): string[] | null {
  switch (rule.action) {
    case 'move_to':
      return rule.targetFolder === null
        ? null
        : [
            `fileinto ${quote(rule.targetFolder)};`,
            `${notifyCall(notify, rule.targetFolder)};`,
            'stop;',
          ];
    case 'mark_read':
      return ['setflag "\\\\Seen";'];
    case 'forward':
      return [`redirect ${quote(rule.conditionValue)};`, 'stop;'];
    case 'discard':
      return ['discard;', 'stop;'];
    default:
      return null;
  }
}

function notifyCall(script: string, folder: string): string {
  return `pipe :copy ${quote(script)} [${quote(folder)}]`;
}

export function generateSieve(rules: readonly FolderRule[], options: SieveOptions): string {
  const junk = options.junkFolder;

  const lines: string[] = [
    'require ["copy", "fileinto", "imap4flags", "mailbox", "vnd.dovecot.pipe"];',
    '',
    '# Generated by stampyx-api. Edits here are overwritten.',
    '',
    'if header :contains "X-Spam-Flag" "YES" {',
    `    fileinto :create ${quote(junk)};`,
    `    ${notifyCall(options.notifyScript, junk)};`,
    '    stop;',
    '}',
    '',
  ];

  for (const rule of [...rules]
    .filter((rule) => rule.active)
    .sort((a, b) => a.position - b.position)) {
    const test = condition(rule);
    const action = body(rule, options.notifyScript);

    if (test === null || action === null) {
      continue;
    }

    lines.push(`if ${test} {`, ...action.map((line) => `    ${line}`), '}', '');
  }

  lines.push(`${notifyCall(options.notifyScript, 'INBOX')};`, '');

  return lines.join('\n');
}
